server:
  port: 8080
  servlet:
    contextPath: /api

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dbcatalogo"
    jmx-enabled: true
    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

